version: "3.8"

services:
  # Keycloak Identity Provider
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev --import-realm
    volumes:
      - ./idp/keycloak.conf:/opt/keycloak/conf/keycloak.conf:ro
      - ./idp/keycloak_data:/opt/keycloak/data
      - ./idp/keycloak-realm.json:/opt/keycloak/data/import/realm.json:ro
    ports:
      - "8005:8005"
    depends_on:
      postgres:
        condition: service_healthy #  Wait for PG to be ready
    networks:
      - keycloak_network

  # Shared PostgreSQL Database for Keycloak & Kong
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: stadb  # Default DB for Keycloak
      POSTGRES_USER: sta
      POSTGRES_PASSWORD: simplepass
    networks:
      - keycloak_network
    volumes:
      - ./idp/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: >
      bash -c "
      docker-entrypoint.sh postgres &
      sleep 5 &&
      psql -U sta -d postgres -tc \"SELECT 1 FROM pg_database WHERE datname = 'kong';\" | grep -q 1 || psql -U sta -d postgres -c 'CREATE DATABASE kong;' &&
      psql -U sta -d postgres -c 'GRANT ALL PRIVILEGES ON DATABASE kong TO sta;' &&
      wait"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sta -d postgres"]
      interval: 5s
      retries: 5

#  kong-migrations:
#    image: kong/kong:latest
#    container_name: kong-migrations
#    command: "kong migrations up && kong migrations #finish"
#    depends_on:
#      - postgres
#    environment:
#      KONG_DATABASE: postgres
#      KONG_PG_DATABASE: kong
#      KONG_PG_HOST: postgres
#      KONG_PG_USER: sta
#      KONG_PG_PASSWORD: simplepass
#    restart: on-failure
#    networks:
#      - keycloak_network
#
#
  # Kong Open-Source API Gateway
#  kong:
#    image: custom-kong-oidc
#    container_name: kong
#    depends_on:
#      - postgres
#    environment:
#      KONG_DATABASE: postgres
#      KONG_PG_DATABASE: kong
#      KONG_PG_HOST: postgres
#      KONG_PG_USER: sta
#      KONG_PG_PASSWORD: simplepass
#      KONG_PROXY_ACCESS_LOG: /dev/stdout
#      KONG_ADMIN_ACCESS_LOG: /dev/stdout
#      KONG_PROXY_ERROR_LOG: /dev/stderr
#      KONG_ADMIN_ERROR_LOG: /dev/stderr
#      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 #ssl
#      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 #ssl
#    ports:
#      - "8000:8000"  # API Proxy (HTTP)
#      - "8443:8443"  # API Proxy (HTTPS)
#      - "8001:8001"  # Admin API (HTTP)
#      - "8444:8444"  # Admin API (HTTPS)
#    networks:
#      - keycloak_network

networks:
  keycloak_network:
    driver: bridge

