version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev --import-realm
    volumes:
      - ./idp/keycloak.conf:/opt/keycloak/conf/keycloak.conf:ro
      - ./idp/keycloak_data:/opt/keycloak/data
      - ./idp/keycloak-realm.json:/opt/keycloak/data/import/realm.json:ro
    ports:
      - "8005:8005"
    depends_on:
      - postgres
    networks:
      - keycloak_network

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: stadb
      POSTGRES_USER: sta
      POSTGRES_PASSWORD: simplepass
    networks:
      - keycloak_network
    volumes:
      - ./idp/postgres_data:/var/lib/postgresql/data

networks:
  keycloak_network:
    driver: bridge

